version: '3'
services:
    client-app:
        build:
            context: ./YeProfspilka.Frontend
        ports:
            - '3000:80'

    api:
        build:
            context: ./YeProfspilka.Backend
        ports:
            - '5001:5001'

    # admin-panel:
    #     build:
    #         context: ./YeProfspilka.Admin
    #     ports:
    #         - '4200:4200'

    nginx:
        build:
            context: ./Nginx
        ports:
            - '80:80'
        depends_on:
            - client-app
            - api
